export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const SET_USER_LOCATION = "SET_USER_LOCATION"
export const GET_SOME_USER = "GET_SOME_USER"

export const LOAD_POSTS = "LOAD_POSTS"
export const LOAD_SINGLE_POST = "LOAD_SINGLE_POST"
export const LIKE_POST = "LIKE_POST"
export const LOAD_UNVERIFIED_POSTS = "LOAD_UNVERIFIED_POSTS"
export const VERIFY_POST = "VERIFY_POST"
export const DELETE_POST = "DELETE_POST"
